# Generated by Django 3.0.6 on 2020-09-14 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
