# Generated by Django 3.0.6 on 2020-09-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20200914_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Product',
            new_name='product',
        ),
    ]
